app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, SelectField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError
from flask_wtf.file import FileAllowed, FileField, FileRequired
from app.models import User
from app import images
import phonenumbers

class PatchCordForm(FlaskForm):
    type = SelectField('Type', validators=[DataRequired()], choices=[('SC-SC', 'sc-sc'), ('SC-LC', 'sc-lc'), ('LC-LC', 'lc-lc')], default='SC-SC')
    length = StringField('Length', validators=[DataRequired()])
    note = StringField('Deskripsi/Status Produk', validators=[DataRequired()])
    in_record_of_transfer = FileField('Berita Acara Masuk', validators=[FileAllowed(images, 'Images only!')])
    out_record_of_transfer = FileField('Berita Acara Keluar', validators=[FileAllowed(images, 'Images only!')])
    submit = SubmitField('Simpan')

class SFPForm(FlaskForm):
    type = SelectField('Type', validators=[DataRequired()], choices=[('SFP', 'sfp'), ('XFP', 'xfp'), ('CFP', 'cfp')], default='SFP')
    length = StringField('Length', validators=[DataRequired()])
    capacity = StringField('Capacity', validators=[DataRequired()])
    serial_number = StringField('Serial Number', validators=[DataRequired()])
    product_number = StringField('Product Number', validators=[DataRequired()])
    note = StringField('Deskripsi/Status Produk', validators=[DataRequired()])
    in_record_of_transfer = FileField('Berita Acara Masuk', validators=[FileAllowed(images, 'Images only!')])
    out_record_of_transfer = FileField('Berita Acara Keluar', validators=[FileAllowed(images, 'Images only!')])
    submit = SubmitField('Simpan')

class IOMForm(FlaskForm):
    type = SelectField('Type', validators=[DataRequired()], choices=[('IOM', 'iom'), ('IMM', 'imm')], default='IOM')
    note = StringField('Deskripsi/Status Produk', validators=[DataRequired()])
    in_record_of_transfer = FileField('Berita Acara Masuk', validators=[FileAllowed(images, 'Images only!')])
    out_record_of_transfer = FileField('Berita Acara Keluar', validators=[FileAllowed(images, 'Images only!')])
    submit = SubmitField('Simpan')

class MDAForm(FlaskForm):
    type = SelectField('Type', validators=[DataRequired()], choices=[('M2O', 'm2o'), ('M2', 'm2')], default='M2O')
    capacity = StringField('Capacity', validators=[DataRequired()])
    note = StringField('Deskripsi/Status Produk', validators=[DataRequired()])
    in_record_of_transfer = FileField('Berita Acara Masuk', validators=[FileAllowed(images, 'Images only!')])
    out_record_of_transfer = FileField('Berita Acara Keluar', validators=[FileAllowed(images, 'Images only!')])
    submit = SubmitField('Simpan')

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from datetime import date
from flask import render_template, redirect, flash, url_for, request, current_app
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.utils import secure_filename
from werkzeug.urls import url_parse
from app.main.forms import PatchCordForm, SFPForm, IOMForm, MDAForm
from app.models import User, Item
from app.decorators import admin_required
from app.main import bp
from app import db, images

@bp.route('/')
@bp.route('/index')
def index():
    if current_user.is_authenticated and current_user.is_admin == True:
        return redirect(url_for('admin.admin'))
    return render_template('main/index.html', title='i-man')

@bp.route('/input', methods=['GET'])
@login_required
def input():
    page = request.args.get('page', 1, type=int)
    items = Item.query.paginate(page, current_app.config['DISPLAY_PER_PAGE'], False)
    next_url = url_for('main.input', page=items.next_num) if items.has_next else None
    prev_url = url_for('main.input', page=items.prev_num) if items.has_prev else None
    return render_template('main/input.html', title='Input Item', items=items.items, \
        next_url=next_url, prev_url=prev_url)

@bp.route('/input/<items>', methods=['GET', 'POST'])
@login_required
def input_item(items):
    if items == 'patch_cord':
        form = PatchCordForm()
        if form.validate_on_submit():
            if request.files['in_record_of_transfer']:
                filename = images.save(request.files['in_record_of_transfer'])
                url_file = images.url(filename)
                item = Item(name='patch_cord', type=form.type.data, in_timestamp= date.today(), \
                    length=form.length.data, note=form.note.data, user_id=current_user.name, \
                        in_filename_record_of_transfer=filename, \
                            in_url_record_of_transfer=url_file)
            else:
                item = Item(name='patch_cord', type=form.type.data, in_timestamp= date.today(), \
                    length=form.length.data, note=form.note.data, user_id=current_user.name)
            db.session.add(item)
            db.session.commit()
            flash(f'Item {item.name}, {item.type} successfully entered!')
            return redirect(url_for('main.input_item', items='patch_cord'))
        return render_template('main/patch_cord.html', title='Input Patch Cord', form=form)
    if items == 'sfp':
        form = SFPForm()
        if form.validate_on_submit():
            if request.files['in_record_of_transfer']:
                filename = images.save(request.files['in_record_of_transfer'])
                url_file = images.url(filename)
                item = Item(name='sfp', type=form.type.data, in_timestamp= date.today(), length=form.length.data, capacity=form.capacity.data, \
                    serial_number=form.serial_number.data, product_number=form.product_number.data, \
                        note=form.note.data, user_id=current_user.name, in_filename_record_of_transfer=filename, \
                            in_url_record_of_transfer=url_file)
            else:
                item = Item(name='sfp', type=form.type.data, in_timestamp= date.today(), length=form.length.data, capacity=form.capacity.data, \
                    serial_number=form.serial_number.data, product_number=form.product_number.data, \
                        note=form.note.data, user_id=current_user.name)
            db.session.add(item)
            db.session.commit()
            flash(f'Item {item.name}, {item.type} successfully entered!')
            return redirect(url_for('main.input_item', items='sfp'))
        return render_template('main/sfp.html', title='SFP', form=form)
    if items == 'iom':
        form = IOMForm()
        if form.validate_on_submit():
            if request.files['in_record_of_transfer']:
                filename = images.save(request.files['in_record_of_transfer'])
                url_file = images.url(filename)
                item = Item(name='iom', type=form.type.data, in_timestamp= date.today(), note=form.note.data, user_id=current_user.name, \
                    in_filename_record_of_transfer=filename, in_url_record_of_transfer=url_file)
            else:
                item = Item(name='iom', type=form.type.data, in_timestamp= date.today(), note=form.note.data, user_id=current_user.name)
            db.session.add(item)
            db.session.commit()
            flash(f'Item {item.name}, {item.type} successfully entered!')
            return redirect(url_for('main.input_item', items='iom'))
        return render_template('main/iom.html', title='IOM/Slot', form=form)
    if items == 'mda':
        form = MDAForm()
        if form.validate_on_submit():
            if request.files['in_record_of_transfer']:
                filename = images.save(request.files['in_record_of_transfer'])
                url_file = images.url(filename)
                item = Item(name='mda', type=form.type.data, in_timestamp= date.today(), capacity=form.capacity.data, \
                    note=form.note.data, user_id=current_user.name, in_filename_record_of_transfer=filename, \
                        in_url_record_of_transfer=url_file)
            else:
                item = Item(name='mda', type=form.type.data, in_timestamp= date.today(), capacity=form.capacity.data, \
                    note=form.note.data, user_id=current_user.name)
            db.session.add(item)
            db.session.commit()
            flash(f'Item {item.name}, {item.type} successfully entered!')
            return redirect(url_for('main.input_item', items='mda'))
        return render_template('main/mda.html', title='MDA', form=form)

@bp.route('/edit/<items>/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_item(items, id):
    if items == 'patch_cord':
        form = PatchCordForm()
        item = Item.query.filter_by(id=id).first()
        if form.validate_on_submit():
            if request.files['in_record_of_transfer']:
                filename = images.save(request.files['in_record_of_transfer'])
                url_file = images.url(filename)
                item.type = form.type.data
                item.length = form.length.data
                item.note = form.note.data
                item.in_filename_record_of_transfer = filename
                item.in_url_record_of_transfer = url_file
            else:
                item.type = form.type.data
                item.length = form.length.data
                item.note = form.note.data
            db.session.commit()
            flash(f'Item {item.name} has been updated!')
            return redirect(url_for('main.input', items=item.name))
        elif request.method == 'GET':
            form.type.data = item.type
            form.length.data = item.length
            form.note.data = item.note
            form.in_record_of_transfer.data = item.in_filename_record_of_transfer
        return render_template('main/patch_cord.html', title='Edit Patch Cord', form=form)
    if items == 'sfp':
        form = SFPForm()
        item = Item.query.filter_by(id=id).first()
        if form.validate_on_submit():
            if request.files['in_record_of_transfer']:
                filename = images.save(request.files['in_record_of_transfer'])
                url_file = images.url(filename)
                item.type = form.type.data
                item.length = form.length.data
                item.capacity = form.capacity.data
                item.serial_number = form.serial_number.data
                item.product_number = form.product_number.data
                item.note = form.note.data
                item.in_filename_record_of_transfer = filename
                item.in_url_record_of_transfer = url_file
            else:
                item.type = form.type.data
                item.length = form.length.data
                item.capacity = form.capacity.data
                item.serial_number = form.serial_number.data
                item.product_number = form.product_number.data
                item.note = form.note.data
            db.session.commit()
            flash(f'Item {item.name} has been updated!')
            return redirect(url_for('main.input', items=item.name))
        elif request.method == 'GET':
            form.type.data = item.type
            form.length.data = item.length
            form.capacity.data = item.capacity
            form.serial_number.data = item.serial_number
            form.product_number.data = item.product_number
            form.note.data = item.note
            form.in_record_of_transfer.data = item.in_filename_record_of_transfer
        return render_template('main/sfp.html', title='Edit SFP', form=form)
    if items == 'iom':
        form = IOMForm()
        item = Item.query.filter_by(id=id).first()
        if form.validate_on_submit():
            if request.files['in_record_of_transfer']:
                filename = images.save(request.files['in_record_of_transfer'])
                url_file = images.url(filename)
                item.type = form.type.data
                item.note = form.note.data
                item.filename_record_of_transfer = filename
                item.in_url_record_of_transfer = url_file
            else:
                item.type = form.type.data
                item.note = form.note.data
            db.session.commit()
            flash(f'Item {item.name} has been updated!')
            return redirect(url_for('main.input', items=item.name))
        elif request.method == 'GET':
            form.type.data = item.type
            form.note.data = item.note
            form.in_record_of_transfer.data = item.in_filename_record_of_transfer
        return render_template('main/iom.html', title='Edit IOM', form=form)
    if items == 'mda':
        form = MDAForm()
        item = Item.query.filter_by(id=id).first()
        if form.validate_on_submit():

app/templates/main/detail.html
{% extends "base.html" %}

{% block content %}
    <div class="content">
        <div>
            {% if item.name == 'patch_cord' %}
                <h1>Detail Item: Patch Cord</h1>
            {% endif %}
            {% if item.name == 'sfp' %}
                <h1>Detail Item: SFP</h1>
            {% endif %}
            {% if item.name == 'iom' %}
                <h1>Detail Item: IOM</h1>
            {% endif %}
            {% if item.name == 'mda' %}
                <h1>Detail Item: MDA</h1>
            {% endif %}
        </div>
        {% if item.type != '-'  %}
            <div>
                <p>Type: {{ item.type }}</p>
            </div>
        {% endif %}
        {% if item.in_timestamp != '-'  %}
            <div>
                <p>Date Added: {{ item.timestamp }}</p>
            </div>
        {% endif %}
        {% if item.user_id != '-'  %}
            <div>
                <p>Added By: {{ item.user_id }}</p>
            </div>
        {% endif %}
        {% if item.serial_number != '-' %}
            <div>
                <p>Serial Number: {{ item.serial_number }}</p>
            </div>
        {% endif %}
        {% if item.product_number != '-' %}
            <div>
                <p>Product Number: {{ item.product_number }}</p>
            </div>
        {% endif %}
        {% if item.length != '-'  %}
            <div>
                <p>Length: {{ item.length }}</p>
            </div>
        {% endif %}
        {% if item.capacity != '-'  %}
            <div>
                <p>Capacity: {{ item.capacity }}</p>
            </div>
        {% endif %}
        {% if item.status != '-'  %}
            <div>
                <p>Note: {{ item.note }}</p>
            </div>
        {% endif %}
        {% if item.note != '-'  %}
            <div>
                <p>Note: {{ item.note }}</p>
            </div>
        {% endif %}
        {% if item.in_url_record_of_transfer == '-' %}
            <div>
                <p>Berita Acara:</p>
                -
            </div>
        {% else %}
            <div>
                <p>Berita Acara Masuk:</p>
                <img src="{{ item.in_url_record_of_transfer }}" alt="{{ item.in_filename_record_of_transfer }}" style="width:600px;height:450px;">
            </div>
        {% endif %}
        {% if item.out_url_record_of_transfer and item.status == 'taken-out' %}
            <div>
                <p>Berita Acara Keluar:</p>
                <img src="{{ item.out_url_record_of_transfer }}" alt="{{ item.out_filename_record_of_transfer }}" style="width:600px;height:450px;">
            </div>
        {% endif %}
    </div>
{% endblock %}

app/templates/main/index.html
{% extends "base.html" %}

{% block content %}
    {% if current_user.is_anonymous %}
        <h1>Welcome to I-MAN</h1>
        <p>Please, login first</p>
    {% elif current_user.is_admin %}
        <h1>Hello, admin {{ current_user.name }}</h1>
        <h1>Welcome to I-MAN</h1>
    {% endif %}
    <p>Made with &hearts; by <a href="https://github.com/pramuditorh">@pramuditorh</a></p>
{% endblock%}

app/templates/main/input.html
{% extends "base.html" %}

{% block content %}
    <style>
        table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        }
        
        td, th {
        border: 1px solid black;
        text-align: left;
        padding: 8px;
        }
        
        tr:nth-child(even) {
        background-color: #dddddd;
        }
    </style>
    <div>Input Item:
        <a href="{{ url_for('main.input_item', items='patch_cord') }}">Patch Cord</a>
        <a href="{{ url_for('main.input_item', items='sfp') }}">SFP</a>
        <a href="{{ url_for('main.input_item', items='iom') }}">IOM</a>
        <a href="{{ url_for('main.input_item', items='mda') }}">MDA</a>
    </div>
    <div>
        <table>
            <thead>
                <tr>
                    <td>No</td>
                    <td>Name</td>
                    <td>Type</td>
                    <td>Date In</td>
                    <td>Serial Number</td>
                    <td>Product Number</td>
                    <td>Length (M)</td>
                    <td>Capacity (G)</td>
                    <td>Status</td>
                    <td>Note</td>
                    <td>Berita Acara Masuk</td>
                    <td>PIC</td>
                    <td colspan="3">Actions</td>
                </tr>
            </thead>
            <tbody>
                {% for item in items %}
                    {% if item.status == 'available' %}
                        <tr>
                            <td>{{ loop.index }}</td>
                            <td>{{ item.name }}</td>
                            <td>{{ item.type }}</td>
                            <td>{{ item.in_timestamp }}</td>
                            <td>{{ item.serial_number }}</td>
                            <td>{{ item.product_number }}</td>
                            <td>{{ item.length }}</td>
                            <td>{{ item.capacity }}</td>
                            <td>{{ item.status }}</td>
                            <td>{{ item.note }}</td>
                            {% if item.in_url_record_of_transfer == '-' %}
                                <td>-</td>
                            {% else %}
                                <td>Ada</a></td>
                            {% endif %}
                            <td>{{ item.user_id }}</td>
                            <td><a href="{{ url_for('main.detail_item', items=item.name, id=item.id) }}">Detail</a></td>
                            <td><a href="{{ url_for('main.edit_item', items=item.name, id=item.id) }}">Edit</a></td>
                            <td><a href="{{ url_for('main.takeout_item', items=item.name, id=item.id) }}">Takeout</a></td>
                        </tr>
                    {% endif %}
                {% endfor %}
            </tbody>
        </table>
        {% if prev_url %}
            <a href="{{ prev_url }}">Previous</a>
        {% endif %}
        {% if next_url %}
            <a href="{{ next_url }}">Next</a>
        {% endif %}
    </div>
{% endblock %}

app/templates/main/iom.html
{% extends "base.html" %}

{% block content %}
    <form action="" method="POST" enctype="multipart/form-data" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.type.label }} <br>
            {{ form.type }} <br>
            {% for error in form.type.errors %}
                <span style="color:red">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.note.label }} <br>
            {{ form.note(size=32) }} <br>
            {% for error in form.note.errors %}
                <span style="color:red">[{{ error }}]</span>
            {% endfor %}
        </p>
        {% if '/takeout' in request.path %}
            {% if item.in_url_record_of_transfer == '-' %}
                <div>
                    <p>Berita Acara:</p>
                    -
                </div>
            {% else %}
                <div>
                    <p>Berita Acara Masuk:</p>
                    <img src="{{ item.in_url_record_of_transfer }}" alt="{{ item.in_filename_record_of_transfer }}" style="width:600px;height:450px;">
                </div>
            {% endif %}
            <p>
                {{ form.out_record_of_transfer.label }} <br>
                {{ form.out_record_of_transfer(size=32) }} <br>
                {% for error in form.out_record_of_transfer.errors %}
                    <span style="color:red">[{{ error }}]</span>
                {% endfor %}
            </p>
        {% else %}
            <p>
                {{ form.in_record_of_transfer.label }} <br>
                {{ form.in_record_of_transfer(size=32) }} <br>
                {% for error in form.in_record_of_transfer.errors %}
                    <span style="color:red">[{{ error }}]</span>
                {% endfor %}
            </p>
        {% endif %}
        <p>
            {{ form.submit() }}
        </p>
    </form>
{% endblock %}

app/templates/main/mda.html
{% extends "base.html" %}

{% block content %}
    <form action="" method="POST" enctype="multipart/form-data" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.type.label }} <br>
            {{ form.type }} <br>
            {% for error in form.type.errors %}
                <span style="color:red">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.capacity.label }} <br>
            {{ form.capacity(size=32) }} <br>
            {% for error in form.capacity.errors %}
                <span style="color:red">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.note.label }} <br>
            {{ form.note(size=32) }} <br>
            {% for error in form.note.errors %}
                <span style="color:red">[{{ error }}]</span>
            {% endfor %}
        </p>
        {% if '/takeout' in request.path %}
            {% if item.in_url_record_of_transfer == '-' %}
                <div>
                    <p>Berita Acara:</p>
                    -
                </div>
            {% else %}
                <div>
                    <p>Berita Acara Masuk:</p>
                    <img src="{{ item.in_url_record_of_transfer }}" alt="{{ item.in_filename_record_of_transfer }}" style="width:600px;height:450px;">
                </div>
            {% endif %}
            <p>
                {{ form.out_record_of_transfer.label }} <br>
                {{ form.out_record_of_transfer(size=32) }} <br>
                {% for error in form.out_record_of_transfer.errors %}
                    <span style="color:red">[{{ error }}]</span>
                {% endfor %}
            </p>
        {% else %}
            <p>
                {{ form.in_record_of_transfer.label }} <br>
                {{ form.in_record_of_transfer(size=32) }} <br>
                {% for error in form.in_record_of_transfer.errors %}
                    <span style="color:red">[{{ error }}]</span>
                {% endfor %}
            </p>
        {% endif %}
        <p>
            {{ form.submit() }}
        </p>
    </form>
{% endblock %}

app/templates/main/patch_cord.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ title }}:</h1>
    <form action="" method="POST" enctype="multipart/form-data" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.type.label }} <br>
            {{ form.type }} <br>
            {% for error in form.type.errors %}
                <span style="color:red">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.length.label }} <br>
            {{ form.length(size=32) }} <br>
            {% for error in form.length.errors %}
                <span style="color:red">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.note.label }} <br>
            {{ form.note(size=32) }} <br>
            {% for error in form.note.errors %}
                <span style="color:red">[{{ error }}]</span>
            {% endfor %}
        </p>
        {% if '/takeout' in request.path %}
            {% if item.in_url_record_of_transfer == '-' %}
                <div>
                    <p>Berita Acara:</p>
                    -
                </div>
            {% else %}
                <div>
                    <p>Berita Acara Masuk:</p>
                    <img src="{{ item.in_url_record_of_transfer }}" alt="{{ item.in_filename_record_of_transfer }}" style="width:600px;height:450px;">
                </div>
            {% endif %}
            <p>
                {{ form.out_record_of_transfer.label }} <br>
                {{ form.out_record_of_transfer(size=32) }} <br>
                {% for error in form.out_record_of_transfer.errors %}
                    <span style="color:red">[{{ error }}]</span>
                {% endfor %}
            </p>
        {% else %}
            <p>
                {{ form.in_record_of_transfer.label }} <br>
                {{ form.in_record_of_transfer(size=32) }} <br>
                {% for error in form.in_record_of_transfer.errors %}
                    <span style="color:red">[{{ error }}]</span>
                {% endfor %}
            </p>
        {% endif %}
        <p>
            {{ form.submit() }}
        </p>
    </form>
{% endblock %}

app/templates/main/sfp.html
{% extends "base.html" %}

{% block content %}
    <form action="" method="POST" enctype="multipart/form-data" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.type.label }} <br>
            {{ form.type }} <br>
            {% for error in form.type.errors %}
                <span style="color:red">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.length.label }} <br>
            {{ form.length(size=32) }} <br>
            {% for error in form.length.errors %}
                <span style="color:red">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.capacity.label }} <br>
            {{ form.capacity(size=32) }} <br>
            {% for error in form.capacity.errors %}
                <span style="color:red">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.serial_number.label }} <br>
            {{ form.serial_number(size=32) }} <br>
            {% for error in form.serial_number.errors %}
                <span style="color:red">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.product_number.label }} <br>
            {{ form.product_number(size=32) }} <br>
            {% for error in form.product_number.errors %}
                <span style="color:red">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.note.label }} <br>
            {{ form.note(size=32) }} <br>
            {% for error in form.note.errors %}
                <span style="color:red">[{{ error }}]</span>
            {% endfor %}
        </p>
        {% if '/takeout' in request.path %}
            {% if item.in_url_record_of_transfer == '-' %}
                <div>
                    <p>Berita Acara:</p>
                    -
                </div>
            {% else %}
                <div>
                    <p>Berita Acara Masuk:</p>
                    <img src="{{ item.in_url_record_of_transfer }}" alt="{{ item.in_filename_record_of_transfer }}" style="width:600px;height:450px;">
                </div>
            {% endif %}
            <p>
                {{ form.out_record_of_transfer.label }} <br>
                {{ form.out_record_of_transfer(size=32) }} <br>
                {% for error in form.out_record_of_transfer.errors %}
                    <span style="color:red">[{{ error }}]</span>
                {% endfor %}
            </p>
        {% else %}
            <p>
                {{ form.in_record_of_transfer.label }} <br>
                {{ form.in_record_of_transfer(size=32) }} <br>
                {% for error in form.in_record_of_transfer.errors %}
                    <span style="color:red">[{{ error }}]</span>
                {% endfor %}
            </p>
        {% endif %}
        <p>
            {{ form.submit() }}
        </p>
    </form>
{% endblock %}

app/templates/main/takeout.html
{% extends "base.html" %}

{% block content %}
    <style>
        table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        }
        
        td, th {
        border: 1px solid black;
        text-align: left;
        padding: 8px;
        }
        
        tr:nth-child(even) {
        background-color: #dddddd;
        }
    </style>
    <div>Input Item:
        <a href="{{ url_for('main.input_item', items='patch_cord') }}">Patch Cord</a>
        <a href="{{ url_for('main.input_item', items='sfp') }}">SFP</a>
        <a href="{{ url_for('main.input_item', items='iom') }}">IOM</a>
        <a href="{{ url_for('main.input_item', items='mda') }}">MDA</a>
    </div>
    <div>
        <table>
            <thead>
                <tr>
                    <td>No</td>
                    <td>Name</td>
                    <td>Type</td>
                    <td>Date In</td>
                    <td>Serial Number</td>
                    <td>Product Number</td>
                    <td>Length (M)</td>
                    <td>Capacity (G)</td>
                    <td>Status</td>
                    <td>Note</td>
                    <td>Berita Acara Masuk</td>
                    <td>PIC</td>
                    <td colspan="3">Actions</td>
                </tr>
            </thead>
            <tbody>
                {% for item in items %}
                    {% if item.status == 'taken-out' %}
                        <tr>
                            <td>{{ loop.index }}</td>
                            <td>{{ item.name }}</td>
                            <td>{{ item.type }}</td>
                            <td>{{ item.in_timestamp }}</td>
                            <td>{{ item.serial_number }}</td>
                            <td>{{ item.product_number }}</td>
                            <td>{{ item.length }}</td>
                            <td>{{ item.capacity }}</td>
                            <td>{{ item.status }}</td>
                            <td>{{ item.note }}</td>
                            {% if item.in_url_record_of_transfer == '-' %}
                                <td>-</td>
                            {% else %}
                                <td>Ada</a></td>
                            {% endif %}
                            <td>{{ item.user_id }}</td>
                            <td><a href="{{ url_for('main.detail_item', items=item.name, id=item.id) }}">Detail</a></td>
                            <td><a href="{{ url_for('main.edit_item', items=item.name, id=item.id) }}">Edit</a></td>
                            <td><a href="{{ url_for('main.takeout_item', items=item.name, id=item.id) }}">Takeout</a></td>
                        </tr>
                    {% endif %}
                {% endfor %}
            </tbody>
        </table>
        {% if prev_url %}
            <a href="{{ prev_url }}">Previous</a>
        {% endif %}
        {% if next_url %}
            <a href="{{ next_url }}">Next</a>
        {% endif %}
    </div>
{% endblock %}